settings:
  title: 'Status Page'
  url: 'https://status.liyp.cc' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-liyp-cc # unique identifier
    name: www.liyp.cc
    description: 'Blog.' # default=empty
    url: 'https://www.liyp.cc/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: git-liyp-cc
    name: git.liyp.cc
    description: 'Gitea Service.'
    url: 'https://git.liyp.cc'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: lobe-chat
    name: Self-host GPT Service 
    url: 'https://g.liyp.cc/'
    method: GET
    expectStatus: 200

  - id: lobe-chat1
    name: Self-host GPT Service 
    url: 'https://gpt.liyp.cc/'
    method: GET
    expectStatus: 200

  - id: Kavita-Service 
    name: Self-host Kavita Service 
    url: 'https://book.liyp.cc/'
    method: GET
    expectStatus: 200

  - id: Alist-Service 
    name: Alist Service 
    url: 'https://pan.liyp.cc/'
    method: GET
    expectStatus: 200
